name: ${project.name}
version: ${project.version}
author: aumgn
website: aumgn.fr

main: fr.aumgn.dac.DAC
depend: [WorldEdit]

commands:
    dac:
        Utilisation: "Utilisation: /<command> join | start | stop | reset | quit | lives | goto"
    dac-define:
        description: 'Defini une nouvelle arene de jeu dans le monde actuel.'
        Utilisation: "Utilisation: /<command> <arene>"
        permission: 'dac.config'
        aliases: ["dac-def"]
    dac-delete:
        description: 'Supprime une arene'
        Utilisation: "Utilisation: /<command> <arene>"
        permission: 'dac.config'
        aliases: ["dac-del", "dac-rm"]
    dac-set:
        description: 'Assigne une zone ou un emplacement.'
        Utilisation: 'Utilisation: /<command> <arene> pool|start|diving'
        permission: 'dac.config'
    dac-select:
        description: 'Charge la zone en tant que selection WorldEdit.'
        Utilisation: 'Utilisation: /<command> <arene> pool|start'
        permission: 'dac.config'
        aliases: ["dac-sel"]
    dac-join:
        description: "Permets de rejoindre une nouvelle partie ou d'en creer une nouvelle."
        Utilisation: 'Utilisation: /<command> [<color> [<color2> [...]]]'
        permission: 'dac.game.play'
        aliases: ["dac-j"]
    dac-start: 
        description: 'Debute une nouvelle partie avec les joueurs presents dans la zone de depart.'
        Utilisation: 'Utilisation: /<command>'
        permission: 'dac.game.play'
        aliases: ["dac-s"]
    dac-stop:
        description: 'Arrete la partie en cours si partie il y a.'
        Utilisation: 'Utilisation: /<command>'
        permission: 'dac.game.manage'
    dac-reset:
        description: "Remplis le bassin d'eau"
        Utilisation: 'Utilisation: /<command> <arene>'
        permission: 'dac.game.manage'
        aliases: ["dac-r"]
    dac-quit:
        description: "Quitter la partie en cours"
        Utilisation: 'Utilisation: /<command>'
        permission: 'dac.game.play'
        aliases: ["dac-q"]
    dac-lives:
        description: 'Affiche le nombre de vies du joueur selectionne ou de tous les joueurs'
        Utilisation: 'Utilisation: /<command> [<joueur>]'
        permission: 'dac.game.play'
    dac-goto:
        description: 'Teleporte le joueur sur le plongeoir ou a sa position de depart'
        Utilisation: 'Utilisation: /<command> diving|start'
        permission: 'dac.game.play'
        aliases: ["dac-g"]
    dac-colors:
        description: "Liste l'ensemble des couleurs disponibles"
        Utilisation: 'Utilisation: /<command>'
        permission: 'dac.game.play'
        
permissions:
    dac.config:
        description: "Permets de mettre en place les zones du jeu."
        default: op
    dac.game.manage:
        description: "Permets de gerer le deroulement d'une partie et de jouer."
        default: op
        children:
            dac.game.play : true
    dac.game.play:
        description: 'Permets de jouer.'
        default: true

