name: ${project.name}
version: ${project.version}
author: aumgn
website: aumgn.fr

main: fr.aumgn.dac.DAC
depend: [WorldEdit]

commands:
    dac:
        usage: "Usage: /<command> join | start | stop | reset | quit | lives | goto"
    dac-define:
        description: 'Defini une nouvelle arene de jeu dans le monde actuel.'
        usage: "Usage: /<command> #arene"
        permission: 'dac.config'
    dac-delete:
        description: 'Supprime une arene'
        usage: "Usage: /<command> #arene"
        permission: 'dac.config'
    dac-set:
        description: 'Assigne une zone ou un emplacement.'
        usage: 'Usage: /<command> #arene pool|start|diving'
        permission: 'dac.config'
    dac-join:
        description: "Permets de rejoindre une nouvelle partie ou d'en creer une nouvelle."
        usage: 'Usage: /<command> [#color [#color2 [...]]]'
        permission: 'dac.game.play'
    dac-start: 
        description: 'Debute une nouvelle partie avec les joueurs presents dans la zone de depart.'
        usage: 'Usage: /<command>'
        permission: 'dac.game.play'
    dac-stop:
        description: 'Arrete la partie en cours si partie il y a.'
        usage: 'Usage: /<command>'
        permission: 'dac.game.manage'
    dac-reset:
        description: "Remplis le bassin d'eau"
        usage: 'Usage: /<command> #arene'
        permission: 'dac.game.manage'
    dac-quit:
        description: "Quitter la partie en cours"
        usage: 'Usage: /<command>'
        permission: 'dac.game.play'
    dac-lives:
        description: 'Affiche le nombre de vies du joueur selectionne ou de tous les joueurs'
        usage: 'Usage: /<command> [#joueur]'
        permission: 'dac.game.play'
    dac-goto:
        description: 'Teleporte le joueur sur le plongeoir ou a sa position de depart'
        usage: 'Usage: /<command> diving|start'
        permission: 'dac.game.play'
    dac-colors:
        description: "Liste l'ensemble des couleurs disponibles"
        usage: 'Usage: /<command>'
        permission: 'dac.game.play'
        
permissions:
    dac.config:
        description: "Permets de mettre en place les zones du jeu."
        default: op
    dac.game.manage:
        description: "Permets de gerer le deroulement d'une partie et de jouer."
        default: op
        children:
            dac.game.play : true
    dac.game.play:
        description: 'Permets de jouer.'
        default: true

